/** Carbon is the single product icon family. Names describe IA2 actions,
 * so changing an icon never changes the control's accessible label. */
export {
  Add as Plus,
  Activity,
  Download as ArrowDownToLine,
  WarningAlt as AlertCircle,
  CheckmarkOutline as CheckCircle,
  CheckmarkOutline as CheckCircle2,
  Time as Clock,
  CircleOutline as Circle,
  ChevronLeft,
  FolderDetails as FolderCheck,
  FolderTree,
  Meter as Gauge,
  Information as Info,
  CircleDash as Loader2,
  PinFilled as PinOff,
  Renew as RefreshCw,
  Rocket,
  DocumentSubject as ScrollText,
  ArrowDown,
  ArrowUp,
  ArrowRight,
  ArrowsHorizontal as ArrowLeftRight,
  Bot,
  Cube as Box,
  Checkmark as Check,
  Checkmark as CheckIcon,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  CircleFilled as CircleIcon,
  Chip as Cpu,
  Code as FileCode2,
  DocumentMultiple_01 as Files,
  Folder,
  FolderOpen,
  FolderAdd as FolderPlus,
  TouchInteraction as Hand,
  Catalog as Library,
  Link as Link2,
  Unlink as Link2Off,
  Locked as Lock,
  Screen as MonitorDot,
  Moon,
  Cursor_1 as MousePointerClick,
  Network_3 as Network,
  SidePanelOpen as PanelRight,
  SidePanelClose as PanelLeftClose,
  SidePanelOpen as PanelLeftOpen,
  Pause,
  Pin,
  Play,
  ConnectionSignal as Radio,
  Undo as RotateCcw,
  Redo as RotateCw,
  Save,
  Search,
  BareMetalServer as Server,
  SettingsAdjust as Settings,
  Warning as ShieldAlert,
  Security as ShieldCheck,
  Stop as Square,
  SkipForward as StepForward,
  Light as Sun,
  TrashCan as Trash2,
  Unlocked as Unlock,
  Close as X,
  Close as XIcon,
  FitToScreen as Maximize,
  Minimize,
  Menu,
} from "@carbon/icons-react"
